name: chennai_nest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # For iOS-style icons
  google_fonts: ^6.1.0     # For custom fonts
  carousel_slider: ^4.2.1  # For image sliders (if needed)
  font_awesome_flutter: ^10.7.0  # For extra icons (Google, Facebook, Instagram, LinkedIn)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/
